/**
 * @file This file is auto-generated by `/scripts/getCategories.js`.
 *       It exists to provide the dropdown options on the site.
 *       The list comes from the css-minify-tests repo.
 */

export const categories = [
  '',
  'anchor',
  'charset',
  'color-rounding',
  'colors',
  'combined',
  'comments',
  'container',
  'counter-style',
  'duplicates',
  'empty-rules',
  'escaping',
  'font-face',
  'gradients',
  'idempotency',
  'import',
  'keyframes',
  'layer',
  'media',
  'merging',
  'nesting',
  'page',
  'property',
  'scope',
  'selectors',
  'selectors-advanced',
  'shorthand-values',
  'shorthands',
  'shorthands-unsafe',
  'starting-style',
  'supports',
  'transforms',
  'values',
  'whitespace',
  'zero-units'
];
