import {
  existsSync,
  readdirSync,
  writeFileSync
} from 'node:fs';
import { join } from 'node:path';

const __dirname = import.meta.dirname;

function getCategories () {
  const cssMinifyTests = join(__dirname, '..', '..', 'css-minify-tests', 'tests');
  if (!existsSync(cssMinifyTests)) {
    console.log([
      '',
      'COPY FAILED:',
      '',
      'You must `git clone` css-minify-tests to:',
      join(__dirname, '..', '..'),
      '',
      'HTTPS',
      'git clone https://github.com/keithamus/css-minify-tests.git',
      '',
      'SSH',
      'git clone git@github.com:keithamus/css-minify-tests.git',
      ''
    ].join('\n'));
    return;
  }
  const categories = readdirSync(cssMinifyTests);
  const output = join(__dirname, '..', 'src', 'helpers', 'categories.js');
  const contents = [
    '/**',
    ' * @file This file is auto-generated by `/scripts/getCategories.js`.',
    ' *       It exists to provide the dropdown options on the site.',
    ' *       The list comes from the css-minify-tests repo.',
    ' */',
    '',
    'export const categories = [',
    '  \'\',\n  \'' + categories.join('\',\n  \'') + '\'',
    '];',
    ''
  ].join('\n');
  writeFileSync(output, contents);
}

getCategories();
